# Generated by Django 3.2.20 on 2023-09-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0002_cart_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="total_price",
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
