# Generated by Django 3.2.20 on 2023-10-08 20:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0004_alter_drink_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drink",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
    ]
