# Generated by Django 3.2.20 on 2023-11-20 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_alter_drink_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
