# Generated by Django 4.1.6 on 2023-03-17 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'drink')},
        ),
    ]
