# Generated by Django 4.0.3 on 2022-10-07 14:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='customer',
        ),
        migrations.AddField(
            model_name='drink',
            name='customer',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='drink',
            name='size',
            field=models.CharField(max_length=5),
        ),
    ]
