# Generated by Django 4.0.3 on 2022-10-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_drink_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='drink',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
