from .base_settings import *

SECURE_HSTS_SECONDS = 315300
SECURE_SSL_REDIRECT = True
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SESSION_COOKIE_SECURE = True
SESSION_COOKING_AGE = 1800
CSRF_COOKIE_SECURE = True
WSGI_APPLICATION = "cronyGlasses.wsgi.application"
ROOT_URLCONF = "cronyGlasses.urls"
