name: Python Tests

on:
  push:
    branches:
      - master
    pull_request:
      branches: ["master"]

env:
  DEBUG: False
  SECRET_KEY: "Not Applicable"
  ALLOWED_HOSTS: "127.0.0.1 localhost"
  SITE_ID: 1

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v3

      - name: update-system-dependencies
        run: |
          sudo apt-get update -y

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.8
          cache: "pip"

      - name: install-python-virtualenv
        run: |
          python3 -m venv venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip==21.2.4
          pip install wheel
          pip install -r requirements.txt

      # - name: collect-static-files
      #   run: |
      #     source venv/bin/activate
      #     python3 manage.py collectstatic --noinput

      - name: run-db-migrations
        run: |
          source venv/bin/activate
          python3 manage.py migrate --noinput

      - name: Run Tests
        run: |
          python3 manage.py test
