name: Python Tests

on:
  push:
    branches:
      - master
    pull_request:
      branches:
        - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: "cronyGlasses.settings.prod"
      SECRET_KEY: "thisisnotasecret"
      PAYPAL_RECEIVER_EMAIL: secrets.PAYPAL_RECEIVER_EMAIL
      USE_SQLITE: True
      ALLOWED_HOSTS: "127.0.0.1 localhost"
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v3

      - name: update-system-dependencies
        run: |
          sudo apt-get update -y

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.8
          cache: "pip"

      - name: Install dependencies, run migrations, and run tests
        run: |
          pip install wheel
          pip install -r requirements.txt
          python manage.py migrate --noinput
          python manage.py test
