name: Python Tests

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.8
          cache: "pip"

      - name: install-python-virtualenv
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install wheel
          pip install -r requirements.txt

      - name: collect-static-files
        run: |
          source venv/bin/activate
          python3 manage.py collectstatic --noinput

      - name: run-db-migrations
        run: |
          source venv/bin/activate
          python3 manage.py migrate --noinput

      - name: Run Tests
        run: |
          python manage.py test
